language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - python3


script:
  - echo "CXX="$CXX
  - echo "CC="$CC
  - if [ "$TRAVIS_OS_NAME" == "linux"]; then if [ "$CXX" = "g++" ]; then sudo apt-get install python3-pip; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux"]; then if [ "$CXX" = "g++" ]; then sudo pip3 install -U pip wheel; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux"]; then if [ "$CXX" = "g++" ]; then sudo pip3 install setuptools; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux"]; then if [ "$CXX" = "g++" ]; then sudo python3 setup.py install; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux"]; then if [ "$CXX" = "g++" ]; then python3 examples/pybullet/unittests/unittests.py --verbose; fi; fi
  - cmake . -DBUILD_PYBULLET=ON -G"Unix Makefiles" #-DCMAKE_CXX_FLAGS=-Werror
  - make -j8
  - ctest -j8 --output-on-failure
  # Build again with double precision
  - cmake . -G "Unix Makefiles" -DUSE_DOUBLE_PRECISION=ON #-DCMAKE_CXX_FLAGS=-Werror
  - make -j8
  - ctest -j8 --output-on-failure
  # Build again with shared libraries
  - cmake . -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON
  - make -j8
  - ctest -j8 --output-on-failure
  - sudo make install
